### ISSUE TITLE
Alias of check is lost for single checking

### ISSUE THREAD

**Issue by mirovsky** [zendframework/ZendDiagnostics#54]
In this loop $alias always will be 0, if $checkAlias is not null
https://github.com/zendframework/ZendDiagnostics/blob/master/src/ZendDiagnostics/Runner/Runner.php#L112

Problem in this line of code:
https://github.com/zendframework/ZendDiagnostics/blob/master/src/ZendDiagnostics/Runner/Runner.php#L106
For example, this will solve this problem:
$checks = $checkAlias ? new ArrayObject(array($checkAlias => $this->getCheck($checkAlias))) : $this->getChecks();

**Comment by mfpierre** [comment]
Encountered this problem while using https://github.com/liip/LiipMonitorBundle the refresh button for a single check was not working properly since the alias is lost in the process.

The solution suggested by @mirovsky is right, it has to be an associative array to keep the alias name
